name: medisafe
description: "Smart Medicine Storage"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Charts and UI
  fl_chart: ^0.64.0
  cupertino_icons: ^1.0.8

  # Storage and preferences
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5

  # Auth and sign-in
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4

  # Media picker
  image_picker: ^1.1.2

  # âœ… Supabase (required for your main.dart)
  supabase_flutter: ^2.6.0
  bcrypt: ^1.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/med_team.png
    - assets/images/jc.jpg
    - assets/images/erel.png
    - assets/images/crespo.jpg
    - assets/images/pengson.png
    - assets/images/tron.jpg
    - assets/images/temp_icon.png
    - assets/images/humidity_icon.png
    - assets/images/sms_icon.png
    - assets/images/navigation_icon.png
    - assets/images/alert_icon.png
    - assets/images/profile_icon.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/logo.png
